const MOCK_PROFILE = {
  "login": "Guibis",
  "id": 105331166,
  "node_id": "U_kgDOBkc53g",
  "avatar_url": "https://avatars.githubusercontent.com/u/105331166?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Guibis",
  "html_url": "https://github.com/Guibis",
  "followers_url": "https://api.github.com/users/Guibis/followers",
  "following_url": "https://api.github.com/users/Guibis/following{/other_user}",
  "gists_url": "https://api.github.com/users/Guibis/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Guibis/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Guibis/subscriptions",
  "organizations_url": "https://api.github.com/users/Guibis/orgs",
  "repos_url": "https://api.github.com/users/Guibis/repos",
  "events_url": "https://api.github.com/users/Guibis/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Guibis/received_events",
  "type": "User",
  "user_view_type": "public",
  "site_admin": false,
  "name": "Guilherme Pereira Lima",
  "company": null,
  "blog": "",
  "location": "Vitória da Conquista - BA",
  "email": null,
  "hireable": null,
  "bio": "Computer engineering student and programming enthusiast.",
  "twitter_username": null,
  "public_repos": 23,
  "public_gists": 0,
  "followers": 1,
  "following": 1,
  "created_at": "2022-05-11T02:01:33Z",
  "updated_at": "2026-01-15T18:41:47Z"
};

const MOCK_REPOS = [
  {
    "id": 1129948513,
    "node_id": "R_kgDOQ1mlYQ",
    "name": "WeatherDashBoard",
    "full_name": "Guibis/WeatherDashBoard",
    "private": false,
    "owner": {
      "login": "Guibis",
      "id": 105331166,
      "avatar_url": "https://avatars.githubusercontent.com/u/105331166?v=4",
      "html_url": "https://github.com/Guibis"
    },
    "html_url": "https://github.com/Guibis/WeatherDashBoard",
    "description": "A modern and responsive weather dashboard",
    "fork": false,
    "url": "https://api.github.com/repos/Guibis/WeatherDashBoard",
    "created_at": "2026-01-07T20:14:21Z",
    "updated_at": "2026-01-16T17:49:25Z",
    "pushed_at": "2026-01-09T05:17:27Z",
    "homepage": "https://guibis.github.io/WeatherDashBoard/",
    "size": 19,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "portfolio"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1119107235,
    "node_id": "R_kgDOQrQ4ow",
    "name": "doce-pomar",
    "full_name": "Guibis/doce-pomar",
    "private": false,
    "owner": {
      "login": "Guibis",
      "id": 105331166,
      "avatar_url": "https://avatars.githubusercontent.com/u/105331166?v=4",
      "html_url": "https://github.com/Guibis"
    },
    "html_url": "https://github.com/Guibis/doce-pomar",
    "description": "Doce Pomar is a simple, responsive website created to showcase a fictional brand that sells seedlings, fruit trees, ornamental plants, and vegetables.",
    "fork": false,
    "url": "https://api.github.com/repos/Guibis/doce-pomar",
    "created_at": "2025-12-18T18:52:49Z",
    "updated_at": "2026-01-16T17:37:54Z",
    "pushed_at": "2026-01-16T02:32:28Z",
    "homepage": "https://guibis.github.io/doce-pomar/",
    "size": 694,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "HTML",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "portfolio"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1123799871,
    "node_id": "R_kgDOQvvTPw",
    "name": "memory",
    "full_name": "Guibis/memory",
    "private": false,
    "owner": {
      "login": "Guibis",
      "id": 105331166,
      "avatar_url": "https://avatars.githubusercontent.com/u/105331166?v=4",
      "html_url": "https://github.com/Guibis"
    },
    "html_url": "https://github.com/Guibis/memory",
    "description": "A fun and interactive memory card game inspired by the One Piece universe. Test your memory skills by matching character cards as fast as possible!",
    "fork": false,
    "url": "https://api.github.com/repos/Guibis/memory",
    "created_at": "2025-12-27T16:43:47Z",
    "updated_at": "2026-01-16T02:29:04Z",
    "pushed_at": "2025-12-27T18:47:12Z",
    "homepage": "https://guibis.github.io/memory/",
    "size": 2890,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "memory-game-project",
      "one-piece-card-game",
      "portfolio"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1126951916,
    "node_id": "R_kgDOQyvr7A",
    "name": "Tomato-Clock",
    "full_name": "Guibis/Tomato-Clock",
    "private": false,
    "owner": {
      "login": "Guibis",
      "id": 105331166,
      "avatar_url": "https://avatars.githubusercontent.com/u/105331166?v=4",
      "html_url": "https://github.com/Guibis"
    },
    "html_url": "https://github.com/Guibis/Tomato-Clock",
    "description": "A minimalist Pomodoro Timer built with HTML, CSS, and JavaScript, designed to help developers stay focused and productive without unnecessary complexity.",
    "fork": false,
    "url": "https://api.github.com/repos/Guibis/Tomato-Clock",
    "created_at": "2026-01-02T22:01:13Z",
    "updated_at": "2026-01-16T02:28:50Z",
    "pushed_at": "2026-01-03T04:33:47Z",
    "homepage": "https://guibis.github.io/Tomato-Clock/",
    "size": 8,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "portfolio"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1131794764,
    "node_id": "R_kgDOQ3XRTA",
    "name": "lumina",
    "full_name": "Guibis/lumina",
    "private": false,
    "owner": {
      "login": "Guibis",
      "id": 105331166,
      "avatar_url": "https://avatars.githubusercontent.com/u/105331166?v=4",
      "html_url": "https://github.com/Guibis"
    },
    "html_url": "https://github.com/Guibis/lumina",
    "description": "Lumina is a premium, interactive web application designed to help developers and designers create beautiful CSS gradients with ease.",
    "fork": false,
    "url": "https://api.github.com/repos/Guibis/lumina",
    "created_at": "2026-01-10T17:54:08Z",
    "updated_at": "2026-01-16T02:05:01Z",
    "pushed_at": "2026-01-10T18:00:23Z",
    "homepage": "https://guibis.github.io/lumina/",
    "size": 11,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "portfolio"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 1133708086,
    "node_id": "R_kgDOQ5MDNg",
    "name": "globalIntelDirectory",
    "full_name": "Guibis/globalIntelDirectory",
    "private": false,
    "owner": {
      "login": "Guibis",
      "id": 105331166,
      "avatar_url": "https://avatars.githubusercontent.com/u/105331166?v=4",
      "html_url": "https://github.com/Guibis"
    },
    "html_url": "https://github.com/Guibis/globalIntelDirectory",
    "description": "Classified // Field Agent Access Only",
    "fork": false,
    "url": "https://api.github.com/repos/Guibis/globalIntelDirectory",
    "created_at": "2026-01-13T18:00:18Z",
    "updated_at": "2026-01-16T02:04:55Z",
    "pushed_at": "2026-01-13T23:51:08Z",
    "homepage": "https://guibis.github.io/globalIntelDirectory/",
    "size": 14,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "portfolio"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1133055132,
    "node_id": "R_kgDOQ4kMnA",
    "name": "pokedex",
    "full_name": "Guibis/pokedex",
    "private": false,
    "owner": {
      "login": "Guibis",
      "id": 105331166,
      "avatar_url": "https://avatars.githubusercontent.com/u/105331166?v=4",
      "html_url": "https://github.com/Guibis"
    },
    "html_url": "https://github.com/Guibis/pokedex",
    "description": "A simple and interactive Pokédex web application that displays Pokémon from Generation I.",
    "fork": false,
    "url": "https://api.github.com/repos/Guibis/pokedex",
    "created_at": "2026-01-12T20:25:05Z",
    "updated_at": "2026-01-16T02:04:35Z",
    "pushed_at": "2026-01-13T02:04:58Z",
    "homepage": "https://guibis.github.io/pokedex/",
    "size": 467,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "portfolio"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1128395894,
    "node_id": "R_kgDOQ0H0dg",
    "name": "beatBox",
    "full_name": "Guibis/beatBox",
    "private": false,
    "owner": {
      "login": "Guibis",
      "id": 105331166,
      "avatar_url": "https://avatars.githubusercontent.com/u/105331166?v=4",
      "html_url": "https://github.com/Guibis"
    },
    "html_url": "https://github.com/Guibis/beatBox",
    "description": "A simple and interactive Drum Kit web application that allows users to play drum sounds",
    "fork": false,
    "url": "https://api.github.com/repos/Guibis/beatBox",
    "created_at": "2026-01-05T15:18:56Z",
    "updated_at": "2026-01-16T02:04:25Z",
    "pushed_at": "2026-01-06T05:19:35Z",
    "homepage": "https://guibis.github.io/beatBox/",
    "size": 336,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "portfolio"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1129080568,
    "node_id": "R_kgDOQ0xm-A",
    "name": "toDoList",
    "full_name": "Guibis/toDoList",
    "private": false,
    "owner": {
      "login": "Guibis",
      "id": 105331166,
      "avatar_url": "https://avatars.githubusercontent.com/u/105331166?v=4",
      "html_url": "https://github.com/Guibis"
    },
    "html_url": "https://github.com/Guibis/toDoList",
    "description": "TaskMaster is a simple yet powerful ToDo List application",
    "fork": false,
    "url": "https://api.github.com/repos/Guibis/toDoList",
    "created_at": "2026-01-06T15:21:39Z",
    "updated_at": "2026-01-16T02:04:18Z",
    "pushed_at": "2026-01-10T19:33:04Z",
    "homepage": "https://guibis.github.io/toDoList/",
    "size": 10,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "portfolio",
      "todolist"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1119804227,
    "node_id": "R_kgDOQr7bQw",
    "name": "tic-tac-toe",
    "full_name": "Guibis/tic-tac-toe",
    "private": false,
    "owner": {
      "login": "Guibis",
      "id": 105331166,
      "avatar_url": "https://avatars.githubusercontent.com/u/105331166?v=4",
      "html_url": "https://github.com/Guibis"
    },
    "html_url": "https://github.com/Guibis/tic-tac-toe",
    "description": "This is a simple and interactive Tic-Tac-Toe game developed using HTML, CSS, and JavaScript. The main highlight of this project is that the background color changes every time the player switches, making the gameplay more dynamic and visually engaging.",
    "fork": false,
    "url": "https://api.github.com/repos/Guibis/tic-tac-toe",
    "created_at": "2025-12-19T22:04:05Z",
    "updated_at": "2026-01-16T02:00:34Z",
    "pushed_at": "2025-12-31T14:30:18Z",
    "homepage": "https://guibis.github.io/tic-tac-toe/",
    "size": 38,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "portfolio",
      "responsive-design",
      "tictactoe-game"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1125299199,
    "node_id": "R_kgDOQxKz_w",
    "name": "snakeGame",
    "full_name": "Guibis/snakeGame",
    "private": false,
    "owner": {
      "login": "Guibis",
      "id": 105331166,
      "avatar_url": "https://avatars.githubusercontent.com/u/105331166?v=4",
      "html_url": "https://github.com/Guibis"
    },
    "html_url": "https://github.com/Guibis/snakeGame",
    "description": "This repository contains a simple implementation of the famous Snake game — a timeless classic where the player controls a growing snake that must eat food while avoiding collisions with walls and itself. The game increases in difficulty as the snake grows longer.",
    "fork": false,
    "url": "https://api.github.com/repos/Guibis/snakeGame",
    "created_at": "2025-12-30T13:33:36Z",
    "updated_at": "2026-01-16T02:00:26Z",
    "pushed_at": "2025-12-31T17:25:13Z",
    "homepage": "https://guibis.github.io/snakeGame/",
    "size": 1265,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "keyboard",
      "portfolio",
      "responsive-website",
      "snake-game"
    ],
    "visibility": "public",
    "forks": 1,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1134300960,
    "node_id": "R_kgDOQ5wPIA",
    "name": "portfolio",
    "full_name": "Guibis/portfolio",
    "private": false,
    "owner": {
      "login": "Guibis",
      "id": 105331166,
      "avatar_url": "https://avatars.githubusercontent.com/u/105331166?v=4",
      "html_url": "https://github.com/Guibis"
    },
    "html_url": "https://github.com/Guibis/portfolio",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Guibis/portfolio",
    "created_at": "2026-01-14T14:33:03Z",
    "updated_at": "2026-01-14T14:33:19Z",
    "pushed_at": "2026-01-16T04:34:37Z",
    "homepage": null,
    "size": 9,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 2,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [],
    "visibility": "public",
    "forks": 0,
    "open_issues": 2,
    "watchers": 0,
    "default_branch": "main"
  }
];
